### ISSUE TITLE
Dataset dowload

### ISSUE THREAD

**Issue by Holmes2002** [ndl-lab/ndl-minhon-ocrdataset#3]
Hi, I want to dowload total dataset but there were a large images still remain due to the limitation of access or error urls. Can u provide total images dataset zip fike link to download ?

**Comment by ndl-lab-staff** [comment]
Hello! Thank you for your request.
Unfortunately, we are unable to provide image files.
This is because the majority of the images used by this dataset are publicly available from universities and research institutes outside of our organization. 
We are not currently considering secondary distribution of their images.
Sorry we could not meet your request.

**Comment by Holmes2002** [comment]
Thank for your response
